version: "3"

volumes:
  # locally bound volume so that the database can be explored on the host
  dbdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './dbdata'

services:
  cerberus-example-app:
    build: .
    container_name: cerberus-example
    ports:
      - "8081:8081"
    environment:
      - APP_PORT=8081
      - JWT_SECRET=${JWT_SECRET}
      - SALT_ROUNDS=10
      - CERBERUS_HOST = "https://cerberus-api.a11n.io:443"
      - CERBERUS_API_KEY = ""
      - CERBERUS_API_SECRET = ${CERBERUS_API_SECRET}

    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - dbdata:/app/dbdata
